name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Fetching repository
      - uses: actions/setup-node@v4 # Installing node
        with:
          node-version-file: '.nvmrc' # Using the same node version as in the project
      - run: npm ci # Installing dependencies

      # Checks:
      - run: npm run lint
      - run: npm run typecheck

      # Build:
      - run: npm run build
