name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Fetching repository
      - uses: actions/checkout@v4

      # Installing node
      - uses: actions/setup-node@v4
        with:
          # Using the same node version as in the project
          node-version-file: '.nvmrc'

      # Dependencies
      - run: corepack enable
      - run: pnpm install

      # Checks:
      - run: npm run lint
      - run: npm run typecheck

      # Build:
      - run: npm run build

      # Tests
      - run: npm run test

      # Todo: Create coverage artifact

      - run: npm run e2e:ci
